export default data = [
	{
		releaseDay: 'monday',
		list: [
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/08/IMG_0534-300x449.png',
				name: 'Niệm vô song',
				engName: 'A moment But Forever',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/09/nghich-thien-chi-ton-300x450.jpg',
				name: 'Nghịch thiên chí tôn',
				engName: 'Ni Tian Zhi Zun',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/doc-bo-tieu-dao-300x450.jpg',
				name: 'Độc bộ tiêu dao',
				engName: 'Du Bu Xiao Yao',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/12/kiem-vuc-phong-van-ss-2-300x450.jpg',
				name: 'Kiếm vực phong vân',
				engName: 'The Legend of Sword Domain',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/07/dai-luc-linh-vo1-300x449.jpg',
				name: 'Đại lục linh võ',
				engName: 'Lingwu Continent',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/04/tan-tu-chi-vuong-300x450.jpg',
				name: 'Tán tu chi vương',
				engName: 'San Xiu Zhi Wang',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/08/van-co-than-thoai-1-300x450.jpg',
				name: 'Vạn cổ thần thoại',
				engName: 'Wangu Shenhua',
				episode: '4',
				update: [4],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/06/kim-tam-vang-su-300x450.jpg',
				name: 'Kim tàm vãng sự',
				engName: 'Jin Can Wangshi',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/vo-thuong-than-de-1-300x450.jpg',
				name: 'Vô thượng thần đế',
				engName: 'Wu Shang Shen Di',
				episode: '4',
				update: [5],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/06/IMG_0531.png',
				name: 'Lục địa kiện tiên',
				engName: 'Keyboard Immortal',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/van-gioi-tien-tung-300x450.webp',
				name: 'Vạn giới tiên tung',
				engName: 'Wan Jie Xian Zong',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/09/cuu-thien-huyen-de-quyet-3-300x450.jpg',
				name: 'Cửu thiên huyền đế hoàng',
				engName: 'The Success Of Empyrean Xuan Emperor',
				episode: '4',
				update: [2],
			},
		],
	},
	{
		releaseDay: 'tuesday',
		list: [
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/thon-phe-tinh-khong-6-300x450.jpg',
				name: 'Swallowed Star',
				engName: 'A moment But Forever',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/02/luyen-khi-10-van-nam-300x450.jpg',
				name: 'Luyện khí mười vạn năm',
				engName: 'Lian Qi Shi Wan Nian',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/vo-than-chua-te-127-300x449.jpg',
				name: 'Võ thần chúa tể',
				engName: 'Wu Shen Zhu Zai',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/08/van-gioi-doc-ton-phan-2-300x449.jpg',
				name: 'Vạn giới độc tôn',
				engName: 'Wan Jie Du Zun Seesion 2',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/04/tuyet-the-chien-hon-300x450.jpg',
				name: 'Tuyệt thế chiên hồn',
				engName: 'Peerless Soul',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/linh-kiem-ton-300x450.jpg',
				name: 'Linh kiếm tôn',
				engName: 'Ling Jian Zun',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/09/doc-bo-van-co-3-300x450.jpg',
				name: 'Độc bộ vạn cổ',
				engName: 'Du Bu Wan Gu',
				episode: '4',
				update: [4],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/03/bach-luyen-phi-thang-luc-300x450.jpg',
				name: 'Bách luyện phi thăng lục',
				engName: 'The Record of Flying Ascension',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/12/dan-dao-chi-ton-300x450.jpeg',
				name: 'Đan đạo chí tôn',
				engName: 'Dan Dao Zhi Zun',
				episode: '4',
				update: [5],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/08/IMG_0535-300x450.png',
				name: 'Wechat của ta thông long cung',
				engName: 'My WeChat Trought Dragon Palace',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/01/thanh-to-1-300x450.jpg',
				name: 'Thánh tổ',
				engName: 'ShengZu',
				episode: '4',
				update: [2],
			},
		],
	},
	{
		releaseDay: 'wednesday',
		list: [
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/tuyet-the-vo-hon-300x450.jpg',
				name: 'Tuyệt thế võ hồn',
				engName: 'Peerless Martial Spirit',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/06/kiem-dao-de-nhat-tien-300x450.jpeg',
				name: 'Kiếm đạo đệ nhất tiên',
				engName: 'Jian Dao Di Yi Xian',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/12/chan-vo-dinh-phong-1-300x450.jpg',
				name: 'Chân võ đỉnh phong',
				engName: 'Zhen Wu Ding Feng',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/03/IMG_0474.jpeg',
				name: 'Chưởng giáo tông môn ẩn thế',
				engName: 'Yin Shi Zong Men Zhang Jiao',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/07/nhat-niem-vinh-hang-phan-3.jpg',
				name: 'Nhất niệm vĩnh hằng',
				engName: ' A Will Eternal Season 3',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/10/gia-thien-5-300x450.jpg',
				name: 'Già thiên',
				engName: 'Shrouding the Heavens',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/08/tay-hanh-ky-dai-vien-hon-300x450.jpg',
				name: 'Tây hành kỷ: Đại viên hồn',
				engName: '大猿魂 特别篇, WuKong',
				episode: '4',
				update: [4],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/08/IMG_0534-300x449.png',
				name: 'Niệm vô song',
				engName: 'A moment But Forever',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/07/IMG_0533-300x450.jpeg',
				name: 'Trảm thần: Phàm trần thần vực',
				engName: 'Zhan Shen',
				episode: '4',
				update: [5],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/07/thieu-nien-bach-ma-tuy-xuan-phong-1-300x450.jpg',
				name: 'Thiếu niên bạch mã túy xuyên phong',
				engName: 'Shao Nian Bai Ma Zui Chun Feng',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/06/thien-dinh-ban-chuyen-hiep-300x450.jpg',
				name: 'Thiên Đình Bản Chuyên Hiệp',
				engName: 'Tian Ting Ban Zhuan Xia',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/06/am-ha-truyen-2-300x450.jpg',
				name: 'Ám hà truyện',
				engName: 'An He Chuan',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/08/tay-hanh-ky-phan-5-1-300x450.jpg',
				name: 'Tây hành kỷ',
				engName: '大猿魂 特别篇, WuKong',
				episode: '4',
				update: [2],
			},
		],
	},
	{
		releaseDay: 'thursday',
		list: [
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/doc-bo-tieu-dao-300x450.jpg',
				name: 'Độc bộ tiêu dao',
				engName: 'Du Bu Xiao Yao',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/12/kiem-vuc-phong-van-ss-2-300x450.jpg',
				name: 'Kiếm vực phong vân',
				engName: 'The Legend of Sword Domain',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/08/van-co-than-thoai-1-300x450.jpg',
				name: 'Vạn cổ thần thoại',
				engName: 'Wangu Shenhua',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/11/van-gioi-chi-ton-1825-300x450.jpg',
				name: 'Vạn giới chí tôn',
				engName: 'Wan Jie Zhi Zun',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/01/su-huynh-a-su-huynh-1-300x450.jpg',
				name: 'Sư huynh a sư huynh',
				engName: 'Shi Xiong A Shi Xiong',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/04/than-an-vuong-toa-3-300x450.jpg',
				name: 'Thần ấn vương tọa',
				engName: 'Throne Of Seal',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/08/kiem-lai-300x450.jpg',
				name: 'Kiếm lai',
				engName: 'Jian Lai',
				episode: '4',
				update: [4],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/05/hoi-minh-phong-hoa-tam-nguyet.jpg',
				name: 'Hồi minh: phong hỏa tâm nguyệt',
				engName: 'Hui Ming Zhi Fengsuo San Yue',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/01/IMG_0206.jpeg',
				name: 'Thái cổ tinh thần quyết',
				engName: 'Tai Gu Xing Shen Jue',
				episode: '4',
				update: [5],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/06/IMG_0531.png',
				name: 'Lục địa kiện tiên',
				engName: 'Keyboard Immortal',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/van-gioi-tien-tung-300x450.webp',
				name: 'Vạn giới tiên tung',
				engName: 'Wan Jie Xian Zong',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/04/bat-diet-than-vuong-300x450.jpeg',
				name: 'Bất diệt thân vương',
				engName: 'Bu Mie Shen Wang',
				episode: '4',
				update: [2],
			},
		],
	},
	{
		releaseDay: 'friday',
		list: [
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/05/phong-van-bien-300x450.jpg',
				name: 'Phong vân biến',
				engName: 'A moment But Forever',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/09/nghich-thien-chi-ton-300x450.jpg',
				name: 'Nghịch thiên chí tôn',
				engName: 'Ni Tian Zhi Zun',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/07/vinh-sinh-phan-4-hai-phe-tien-linh-300x450.jpg',
				name: 'Vĩnh sinh',
				engName: 'Immortality SS4',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/10/bach-luyen-thanh-than-2-300x450.jpg',
				name: 'Bách luyện thành thần',
				engName: 'Elevation to the Status of a God',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/07/dai-luc-linh-vo1-300x449.jpg',
				name: 'Đại lục linh võ',
				engName: 'Lingwu Continent',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/linh-kiem-ton-300x450.jpg',
				name: 'Linh kiếm tôn',
				engName: 'Ling Jian Zun',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/09/doc-bo-van-co-3-300x450.jpg',
				name: 'Độc bộ vạn cổ',
				engName: 'Du Bu Wan Gu',
				episode: '4',
				update: [4],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/03/bach-luyen-phi-thang-luc-300x450.jpg',
				name: 'Bách luyện phi thăng lục',
				engName: 'The Record of Flying Ascension',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/12/dan-dao-chi-ton-300x450.jpeg',
				name: 'Đan đạo chí tôn',
				engName: 'Dan Dao Zhi Zun',
				episode: '4',
				update: [5],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/08/IMG_0535-300x450.png',
				name: 'Wechat của ta thông long cung',
				engName: 'My WeChat Trought Dragon Palace',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/04/the-gioi-hoan-my-tap-dac-biet-300x450.jpg',
				name: 'Thế giới hoàn mỹ',
				engName: 'Perfect World',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/09/cuu-thien-huyen-de-quyet-3-300x450.jpg',
				name: 'Cửu thiên huyền đế hoàng',
				engName: 'The Success Of Empyrean Xuan Emperor',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/05/toan-chuc-cao-thu-300x450.jpg',
				name: 'Toàn chức cao thủ',
				engName: 'The Kings Avatar',
				episode: '4',
				update: [2],
			},
		],
	},
	{
		releaseDay: 'saturday',
		list: [
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/06/bat-dau-tu-co-hoach-dieu-long-thanh-phong-van-300x450.jpg',
				name: 'Bắt đầu từ cô hoạch điểu: long thành phong vân',
				engName: 'Cong Gu Huo Niao Kai Shi Zhi Long Cheng Feng Yun',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/12/chan-vo-dinh-phong-1-300x450.jpg',
				name: 'Chân võ đỉnh phong',
				engName: 'Zhen Wu Ding Feng',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/06/than-mo-1264-2-300x450.jpg',
				name: 'Thần mộ',
				engName: 'Tomb Of Fallen Gods',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/07/than-vo-thien-ton-300x450.jpg',
				name: 'Thần võ thiên tôn',
				engName: 'The Legend of Sky Lord',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/02/luyen-khi-10-van-nam-300x450.jpg',
				name: 'Luyện khí mười vạn năm',
				engName: 'Lian Qi Shi Wan Nian',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/08/van-gioi-doc-ton-phan-2-300x449.jpg',
				name: 'Vạn giới độc tôn',
				engName: 'Wan Jie Du Zun Seesion 2',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/04/tuyet-the-chien-hon-300x450.jpg',
				name: 'Tuyệt thế chiến hồn',
				engName: 'Peerless Soul',
				episode: '4',
				update: [4],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/11/pham-nhan-tu-tien-phan-3-1-300x450.png',
				name: 'Phàm nhân tu tiên',
				engName: 'Fanren Xiu Xian Chuan SS3',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/03/IMG_0474.jpeg',
				name: 'Chưởng giáo tông môn ẩn thế',
				engName: 'Yin Shi Zong Men Zhang Jiao',
				episode: '4',
				update: [5],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/06/dau-la-dai-luc-phan-2-1-300x450.jpg',
				name: 'Đấu la đại lục 2: tuyệt thế đường môn',
				engName: 'Douluo Dalu II: Jue Shi Tang Men',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/05/IMG_0525-300x450.webp',
				name: 'Kim ngô vệ: phong khởi kim lăng',
				engName: 'Jin Wu Wei Zhi Feng Qi Jin Ling',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/12/bang-hoa-ma-tru-2-300x450.jpg',
				name: 'Băng hỏa ma trù',
				engName: 'The Magic Chef Of Ice and Fire',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/06/thuong-nguyen-do-1-300x450.jpg',
				name: 'Thương nguyên đồ',
				engName: 'Cang Yuan Tu',
				episode: '4',
				update: [2],
			},
		],
	},
	{
		releaseDay: 'sunday',
		list: [
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/07/o-re-phan-2-300x450.jpg',
				name: 'Ở rể phần 2',
				engName: 'My Heroic Husband 2',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/05/huyen-sung-su-300x450.png',
				name: 'Huyễn sủng sư',
				engName: 'Huan Chong Shi',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2023/03/tien-vo-de-ton-p2-300x450.jpg',
				name: 'Tiên võ đế tôn',
				engName: 'Xian Wu Di Zun',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/08/Than-Vuc-Vo-Tan.jpg',
				name: 'Thần vực vô tận',
				engName: 'Eternal Realm',
				episode: '4',
				update: [3],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/tuyet-the-vo-hon-300x450.jpg',
				name: 'Tuyệt thế võ hồn',
				engName: 'Peerless Martial Spirit',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/11/van-gioi-chi-ton-1825-300x450.jpg',
				name: 'Vạn giới chí tôn',
				engName: 'Wan Jie Zhi Zun',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/vo-than-chua-te-127-300x449.jpg',
				name: 'Võ thần chúa tể',
				engName: 'Wu Shen Zhu Zai',
				episode: '4',
				update: [4],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2022/06/dau-pha-thuong-khung-phan-5-gia-nam-hoc-vien-1-1-300x450.jpg',
				name: 'Đấu phá thương khung phần 5',
				engName: 'Fights Break Sphere 5',
				episode: '4',
				update: [2],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/01/IMG_0206.jpeg',
				name: 'Thái cổ tinh thầN quyết',
				engName: 'Tai Gu Xing Shen Jue',
				episode: '4',
				update: [5],
			},
			{
				src: 'https://hoathinh3d.run/wp-content/uploads/2024/02/IMG_0349-300x450.jpeg',
				name: 'nhất thế chí tôn',
				engName: 'Ancient Lords',
				episode: '4',
				update: [2],
			},
		],
	},
];

export const movie = {
	name: 'Tiên Nghịch',
	engName: 'Xian Ni',
	types: ['CN Animation', 'Cổ trang', 'Tiên hiệp', 'Huyền Huyễn'],
	image: 'https://hoathinh3d.run/wp-content/uploads/2023/09/tien-nghich-2-300x450.jpg',
	newEpisode: 'Tập 64',
	update: [2],
	otherInfo: {
		released: 2023,
		total: 76,
	},
	rating: {
		total: 1792,
		star: 4.11,
	},
	seasons: [],
	episodes: [
		{ episode: 64 },
		{ episode: 63 },
		{ episode: 62 },
		{ episode: 61 },
		{ episode: 60 },
		{ episode: 59 },
		{ episode: 58 },
		{ episode: 57 },
		{ episode: 56 },
		{ episode: 55 },
		{ episode: 54 },
		{ episode: 53 },
		{ episode: 52 },
		{ episode: 51 },
		{ episode: 50 },
		{ episode: 49 },
		{ episode: 48 },
		{ episode: 47 },
		{ episode: 46 },
		{ episode: 45 },
		{ episode: 44 },
		{ episode: 43 },
		{ episode: 42 },
		{ episode: 41 },
		{ episode: 40 },
		{ episode: 39 },
		{ episode: 38 },
		{ episode: 37 },
		{ episode: 36 },
		{ episode: 35 },
		{ episode: 34 },
		{ episode: 33 },
		{ episode: 32 },
		{ episode: 31 },
		{ episode: 30 },
		{ episode: 29 },
		{ episode: 28 },
		{ episode: 27 },
		{ episode: 26 },
		{ episode: 25 },
		{ episode: 24 },
		{ episode: 23 },
		{ episode: 22 },
		{ episode: 21 },
		{ episode: 20 },
		{ episode: 19 },
		{ episode: 18 },
		{ episode: 17 },
		{ episode: 16 },
		{ episode: 15 },
		{ episode: 14 },
		{ episode: 13 },
		{ episode: 12 },
		{ episode: 11 },
		{ episode: 10 },
		{ episode: 9 },
		{ episode: 8 },
		{ episode: 7 },
		{ episode: 6 },
		{ episode: 5 },
		{ episode: 4 },
		{ episode: 3 },
		{ episode: 2 },
		{ episode: 1 },
	],
	isFollowed: false,
	description: [
		'Một ngày nọ, thế giới xuất hiện loại virus RR không rõ lai lịch, cuốn thế giới vào thảm hoạ. Động vật bị truyền nhiễm đột biến thành quái thú đáng sợ, xâm lược với số lượng lớn. Trong lúc loài người đối mặt với diệt vong, họ đã xây lên bức tường bao vây, thành lập căn cứ làm pháo đài cuối cùng bảo vệ con người.',
		'Trong thời gian này, con người nếm trải đủ mọi khó khăn, được gọi là “thời kỳ Đại Niết Bàn”. Trong môi trường sinh tồn cực đoan, bản năng của con người cũng dần phát triển, ngọn gió thượng võ phất lên, tố chất cơ thể con người vượt trội hơn trước. Mà trong những người xuất sắc, được gọi là “chiến binh”. La Phong năm 18 tuổi cũng ước mơ trở thành một trong số họ. Cậu lúc này sắp phải thi đại học, đang đối diện với sự lựa chọn giữa ngã tư đời người. Nhưng lại bị quái thú tấn công ảnh hưởng quỹ đạo cuộc đời của cậu hết lần này đến lần khác.',
		'Dưới uy hiếp của quái thú, cư dân trong thành phố đối diện với nguy hiểm, quân sự lại bó tay. Duy chỉ có chiến binh xông pha, bảo vệ an toàn cho căn cứ. La Phong được những chiến binh truyền cảm hứng, âm thầm hạ quyết tâm trở thành chiến binh bảo vệ người mình yêu thương. Đây chính là khởi đầu của mọi thứ, khởi điểm của  con đường chiến binh La Phong, cũng vén bức màn cuộc đời truyền kì của cậu. La Phong lập chí trở thành chiến binh. Con đường phía không dễ dàng, đầu tiên cậu phải đối diện với môi trường ngoại bộ, vô hình chung càng thêm ảnh hưởng tới cậu. Gia đình La Phong có điều kiện không tốt, cuộc sống túng thiếu, bố mẹ không thể giúp đỡ cậu được nhiều, cậu đành dựa vào nỗ lực của bản thân.',
		'Cuối cùng, dưới sự khổ luyện, La Phong không ngừng khai quật ra tiềm năng của mình, nhận được sự nâng cấp năng lực với sự công nhận giá trị bản thân. Không những vậy, La Phong còn gánh vác gánh nặng nuôi dưỡng  gia đình, cũng vì bảo vệ tổ quốc loài người, vì cuộc sống sinh tồn và phát triển tốt hơn của con người. Cùng với những chiến binh chính nghĩa khác, liên minh đối phó quái thú hung ác. Dưới tình cảnh tận thế, La Phong cùng với những chiến binh khác liệu có thể đẩy lùi quái thú, thành công bảo vệ thế giới loài người?',
		'Main: La Phong',
		'Vợ: Từ Hân',
		'Các cấp độ:',
		'– Trường phái: Vũ giả – Tinh Thần Niệm Sư (Bậc Thầy Tinh Thần) Khống Vật – Tinh Thần Niệm Sư (Bậc Thầy Tinh Thần) Huyễn thuật – Tề Dược Sư…',
		'– Trình độ địa cầu: Chiến sĩ – Chiến tướng – Chiến thần ( Trực thuộc cấp Học đồ )',
		'– Trình độ toàn vũ trụ:',
		'Học đồ – Hành tinh – Hằng tinh – Vũ trụ – Vực chủ – Giới chủ – Bất hủ – Bất hủ quân chủ – Bất hủ phong Hầu – Bất hủ phong Vương – Vũ trụ tôn giả – Vũ trụ bá chủ (Vũ trụ tôn giả vô địch) – Vũ trụ chi chủ (lực chiến 1-6) – Vũ trụ tối cường giả = Chân thần (lực chiến > 6) – Hư không chân thần (lực chiến > 10) – Vĩnh hằng chân thần – Hỗn Độn chúa tể – Thần vương – Hỗn nguyên – Lãnh chúa.',
	],
};
