export const movie = {
	engName: 'Hua Jiang Hu Zhi Bu Liang Ren',
	src: 'https://hoathinh3d.run/wp-content/uploads/2023/09/tien-nghich-2-300x450.jpg',
	poster: 'https://homepage.momocdn.net/blogscontents/momo-amazone-s3-api-240819164320-638596826005331876.jpeg',
	nameImg: require('../../assets/name-img/tiennghich.png'),
	name: 'Tiên Nghịch',
	types: ['CN Animation', 'Cổ trang', 'Kiếm hiệp'],
	season: 'Phần 6',
	newEpisode: 'HD Vietsub',
	update: [3, 6],
	otherInfo: {
		released: 2023,
		total: 12,
	},
	rating: {
		total: 1792,
		star: 4.11,
	},
	seasons: [
		{ season: 'Phần 1' },
		{ season: 'Phần 2' },
		{ season: 'Phần 3' },
		{ season: 'Phần 4' },
		{ season: 'Phần 5' },
		{ season: 'Phần 6' },
	],
	episodes: [
		{ episode: 64 },
		{ episode: 63 },
		{ episode: 62 },
		{ episode: 61 },
		{ episode: 60 },
		{ episode: 59 },
		{ episode: 58 },
		{ episode: 57 },
		{ episode: 56 },
		{ episode: 55 },
		{ episode: 54 },
		{ episode: 53 },
		{ episode: 52 },
		{ episode: 51 },
		{ episode: 50 },
		{ episode: 49 },
		{ episode: 48 },
		{ episode: 47 },
		{ episode: 46 },
		{ episode: 45 },
		{ episode: 44 },
		{ episode: 43 },
		{ episode: 42 },
		{ episode: 41 },
		{ episode: 40 },
		{ episode: 39 },
		{ episode: 38 },
		{ episode: 37 },
		{ episode: 36 },
		{ episode: 35 },
		{ episode: 34 },
		{ episode: 33 },
		{ episode: 32 },
		{ episode: 31 },
		{ episode: 30 },
		{ episode: 29 },
		{ episode: 28 },
		{ episode: 27 },
		{ episode: 26 },
		{ episode: 25 },
		{ episode: 24 },
		{ episode: 23 },
		{ episode: 22 },
		{ episode: 21 },
		{ episode: 20 },
		{ episode: 19 },
		{ episode: 18 },
		{ episode: 17 },
		{ episode: 16 },
		{ episode: 15 },
		{ episode: 14 },
		{ episode: 13 },
		{ episode: 12 },
		{ episode: 11 },
		{ episode: 10 },
		{ episode: 9 },
		{ episode: 8 },
		{ episode: 7 },
		{ episode: 6 },
		{ episode: 5 },
		{ episode: 4 },
		{ episode: 3 },
		{ episode: 2 },
		{ episode: 1 },
	],
	isFollowed: false,
	description: [
		'Cải biên từ tiểu thuyết “Tiên Nghịch” của tác giả Nhĩ Căn, kể về thiếu niên bình phàm Vương Lâm xuất thân nông thôn, mang theo nhiệt huyết, tu luyện nghịch tiên, không chỉ cầu trường sinh, mà còn muốn thoát khỏi thân phận giun dế. Hắn tin rằng đạo do người quyết định, dùng tư chất bình phàm bước vào con đường tu chân, trải qua bao phong ba bão táp, dựa vào trí tuệ sáng suốt, từng bước một bước lên đỉnh cao, dựa vào sức một người, danh chấn Tu chân giới.',
	],
};

export const comments = [
	{
		img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
		content: 'Anh ngầu ác luôn',
		name: 'Quang Nguyen',
		createdDate: new Date('2024-09-10T16:46:44.124Z'),
		likeCount: 10,
		level: {
			index: 3,
			name: 'Kim đan',
		},
		commentsReply: [
			{
				replyTo: 'Quang Nguyen',
				img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
				content: 'Pro',
				name: 'Quang Nguyen',
				createdDate: new Date('2024-09-10T16:46:44.124Z'),
				likeCount: 10,
				level: {
					index: 5,
					name: 'Hoá thần',
				},
				commentsReply: [
					{
						img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
						replyTo: 'Quang Nguyen',
						content: 'Anh ngầu ác luôn',
						name: 'Quang Nguyen',
						createdDate: new Date('2024-09-10T16:46:44.124Z'),
						likeCount: 10,
						level: {
							index: 3,
							name: 'Kim đan',
						},
						commentsReply: [
							{
								img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
								replyTo: 'Quang Nguyen',
								content: 'Anh ngầu ác luôn',
								name: 'Quang Nguyen',
								createdDate: new Date('2024-09-10T16:46:44.124Z'),
								likeCount: 10,
								level: {
									index: 3,
									name: 'Kim đan',
								},
								commentsReply: [
									{
										img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
										replyTo: 'Quang Nguyen',
										content: 'Anh ngầu ác luôn',
										name: 'Quang Nguyen',
										createdDate: new Date('2024-09-10T16:46:44.124Z'),
										likeCount: 10,
										level: {
											index: 3,
											name: 'Kim đan',
										},
										commentsReply: [
											{
												img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
												replyTo: 'Quang Nguyen',
												content: 'Anh ngầu ác luôn',
												name: 'Quang Nguyen',
												createdDate: new Date('2024-09-10T16:46:44.124Z'),
												likeCount: 10,
												level: {
													index: 3,
													name: 'Kim đan',
												},
												commentsReply: [
													{
														img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
														replyTo: 'Quang Nguyen',
														content: 'Anh ngầu ác luôn',
														name: 'Quang Nguyen',
														createdDate: new Date(
															'2024-09-10T16:46:44.124Z'
														),
														likeCount: 10,
														level: {
															index: 3,
															name: 'Kim đan',
														},
														commentsReply: [
															{
																img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
																replyTo: 'Quang Nguyen',
																content: 'Anh ngầu ác luôn',
																name: 'Quang Nguyen',
																createdDate: new Date(
																	'2024-09-10T16:46:44.124Z'
																),
																likeCount: 10,
																level: {
																	index: 3,
																	name: 'Kim đan',
																},
																commentsReply: [
																	{
																		img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
																		replyTo: 'Quang Nguyen',
																		content: 'Anh ngầu ác luôn',
																		name: 'Quang Nguyen',
																		createdDate: new Date(
																			'2024-09-10T16:46:44.124Z'
																		),
																		likeCount: 10,
																		level: {
																			index: 3,
																			name: 'Kim đan',
																		},
																		commentsReply: [
																			{
																				img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
																				replyTo:
																					'Quang Nguyen',
																				content:
																					'Anh ngầu ác luôn',
																				name: 'Quang Nguyen',
																				createdDate:
																					new Date(
																						'2024-09-10T16:46:44.124Z'
																					),
																				likeCount: 10,
																				level: {
																					index: 3,
																					name: 'Kim đan',
																				},
																				commentsReply: [],
																			},
																		],
																	},
																],
															},
														],
													},
												],
											},
										],
									},
								],
							},
							{
								img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
								replyTo: 'Quang Nguyen',
								content:
									'Anh ngầu ác luônAnh ngầu ác luônAnh ngầu ác luônAnh ngầu ác luônAnh ngầu ác luônAnh ngầu ác luônAnh ngầu ác luôn',
								name: 'Quang Nguyen',
								createdDate: new Date('2024-09-10T16:46:44.124Z'),
								likeCount: 10,
								level: {
									index: 5,
									name: 'Hoá thần',
								},
								commentsReply: [],
							},
						],
					},
				],
			},
			{
				img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
				replyTo: 'Quang Nguyen',
				content: 'Anh ngầu ác luôn',
				name: 'Quang Nguyen',
				createdDate: new Date('2024-09-10T16:46:44.124Z'),
				likeCount: 10,
				level: {
					index: 5,
					name: 'Hoá thần',
				},
				commentsReply: [],
			},
		],
	},
	{
		img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
		content: 'Anh ngầu ác luôn',
		name: 'Quang Nguyen',
		createdDate: new Date('2024-08-25'),
		likeCount: 10,
		level: {
			index: 2,
			name: 'Trúc cơ',
		},
		commentsReply: [],
	},
	{
		img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
		content: 'Anh ngầu ác luôn',
		name: 'Quang Nguyen',
		createdDate: new Date('2024-09-10T16:46:44.124Z'),
		likeCount: 10,
		level: {
			index: 5,
			name: 'Hoá thần',
		},
		commentsReply: [],
	},
	{
		img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
		content: 'Anh ngầu ác luôn',
		name: 'Quang Nguyen',
		createdDate: new Date('2024-09-10T16:46:44.124Z'),
		likeCount: 10,
		level: {
			index: 4,
			name: 'Nguyên Anh',
		},
		commentsReply: [],
	},
	{
		img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
		content: 'Anh ngầu ác luôn',
		name: 'Sinh Hùng',
		createdDate: new Date('2024-09-10T16:46:44.124Z'),
		likeCount: 10,
		level: {
			index: 1,
			name: 'Luyện khí',
		},
		commentsReply: [],
	},
	{
		img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
		content: 'Anh ngầu ác luôn',
		name: 'Tà Ma đại đế',
		createdDate: new Date('2024-09-10T16:46:44.124Z'),
		likeCount: 10,
		level: {
			index: 6,
			name: 'Phân thần',
		},
		commentsReply: [],
	},
	{
		img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
		content: 'Anh ngầu ác luôn',
		name: 'Tà Ma đại đế',
		createdDate: new Date('2024-09-10T16:46:44.124Z'),
		likeCount: 10,
		level: {
			index: 6,
			name: 'Phân thần',
		},
		commentsReply: [],
	},
	{
		img: 'https://hoathinh3d.run/wp-content/uploads/ultimatemember/30703/profile_photo.jpg?1724214785',
		content: 'Anh ngầu ác luôn',
		name: 'Tà Ma đại đế',
		createdDate: new Date('2024-09-10T16:46:44.124Z'),
		likeCount: 10,
		level: {
			index: 6,
			name: 'Phân thần',
		},
		commentsReply: [],
	},
];
