export const view = [
	{
		icon: require('../../assets/popcorn.png'),
		name: 'Coming soon',
	},
	{
		icon: require('../../assets/fire.png'),
		name: "Everyone's watching",
	},
	{
		icon: require('../../assets/top10.png'),
		name: 'Top 10 Kmovie',
	},
];

export const upcoming = [
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2023/10/tap-do-300x450.jpg',
		poster: 'https://i.pinimg.com/736x/34/e2/8d/34e28d15790edc089aaaab48a5305399.jpg',
		nameImg: require('../../assets/name-img/tapdo.png'),
		name: 'Tạp đồ',
		engName: 'KaTu',
		types: ['Hiện Đại'],
		isRelease: false,
		description: [
			'Hàng trăm năm trước, hàng loạt thiên thạch bất ngờ đâm vào hai lục địa cùng tồn tại với nhau và hoàn toàn bị cô lập. Để cứu nền văn minh nhân loại đang bị đe dọa, hàng trăm nhà khoa học lục địa trước đây do Rosenberg dẫn đầu đã tập hợp nỗ lực của nhiều quốc gia khác nhau để phát triển một loại thiết bị cung cấp năng lượng mới (thẻ). Nhân vật chính Trần Mộ từ một thanh niên yếu đuối, nghèo khổ và bất lực, sau khi trải qua một loạt các cuộc phiêu lưu đầy đấu tranh và khó khăn, nhưng vẫn ko bỏ cuộc, vẫn dựa vào bản chất tốt bụng, những nỗ lực vượt trội của bản thân và sự nhiệt tình của người thân và bạn bè xung quanh, cuối cùng đã vượt qua nhiều trở ngại và phát triển thành một nhà lãnh đạo tích cực, chính trực, đạo đức và có năng lực.',
		],
	},
	{
		releasedDate: new Date('2024-12-26'),
		name: 'Song Sinh Võ Hồn',
		nameImg: require('../../assets/name-img/songsinh.png'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2023/02/song-sinh-vo-hon-300x450.jpg',
		poster: 'https://pic-bstarstatic.akamaized.net/ugc/1c634e83a90bfd3ebb70735749f6f707.jpg',
		engName: 'Twin Martial Souls',
		types: ['Huyền huyễn', 'Hiện đại'],
		isRelease: false,
		description: [
			'Xuất thân từ thế gia Quận Đại Lâm, Lâm Phàm vốn là thiên tài tuyệt thế nhận được Thiên Kiêu Lệnh, lại bị vị hôn thê cướp đi Vũ Hồn, trở thành phế vật. Khi đại ma ký sinh Lâm Phàm lai lịch khó lường, một lần nữa kích hoạt vũ hồn hắn bị phế, khiến hắn trở thành thể chất song võ hồn hiếm có, đến lúc này, Lâm Phàm chính thức bước lên con đường quật khởi, từ tiểu quận thành, xông lên chư thiên vạn giới.	',
		],
	},
];

export const recommend = [
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/thon-phe-tinh-khong-6-300x450.jpg',
		poster: 'https://image.tmdb.org/t/p/original/n40e0jtHdDCF2u8Kpps8K2Mx03B.jpg',
		nameImg: require('../../assets/name-img/thonphe.png'),
		name: 'Thôn Phệ Tinh Không',
		engName: 'Swallowed Star',
		types: ['Hiện Đại', 'Huyền huyễn'],
		isRelease: true,
		description: [
			'Một ngày nọ, thế giới xuất hiện loại virus RR không rõ lai lịch, cuốn thế giới vào thảm hoạ. Động vật bị truyền nhiễm đột biến thành quái thú đáng sợ, xâm lược với số lượng lớn. Trong lúc loài người đối mặt với diệt vong, họ đã xây lên bức tường bao vây, thành lập căn cứ làm pháo đài cuối cùng bảo vệ con người.',
			'Trong thời gian này, con người nếm trải đủ mọi khó khăn, được gọi là “thời kỳ Đại Niết Bàn”. Trong môi trường sinh tồn cực đoan, bản năng của con người cũng dần phát triển, ngọn gió thượng võ phất lên, tố chất cơ thể con người vượt trội hơn trước. Mà trong những người xuất sắc, được gọi là “chiến binh”. La Phong năm 18 tuổi cũng ước mơ trở thành một trong số họ. Cậu lúc này sắp phải thi đại học, đang đối diện với sự lựa chọn giữa ngã tư đời người. Nhưng lại bị quái thú tấn công ảnh hưởng quỹ đạo cuộc đời của cậu hết lần này đến lần khác.',
			'Dưới uy hiếp của quái thú, cư dân trong thành phố đối diện với nguy hiểm, quân sự lại bó tay. Duy chỉ có chiến binh xông pha, bảo vệ an toàn cho căn cứ. La Phong được những chiến binh truyền cảm hứng, âm thầm hạ quyết tâm trở thành chiến binh bảo vệ người mình yêu thương. Đây chính là khởi đầu của mọi thứ, khởi điểm của  con đường chiến binh La Phong, cũng vén bức màn cuộc đời truyền kì của cậu. La Phong lập chí trở thành chiến binh. Con đường phía không dễ dàng, đầu tiên cậu phải đối diện với môi trường ngoại bộ, vô hình chung càng thêm ảnh hưởng tới cậu. Gia đình La Phong có điều kiện không tốt, cuộc sống túng thiếu, bố mẹ không thể giúp đỡ cậu được nhiều, cậu đành dựa vào nỗ lực của bản thân.',
			'Cuối cùng, dưới sự khổ luyện, La Phong không ngừng khai quật ra tiềm năng của mình, nhận được sự nâng cấp năng lực với sự công nhận giá trị bản thân. Không những vậy, La Phong còn gánh vác gánh nặng nuôi dưỡng  gia đình, cũng vì bảo vệ tổ quốc loài người, vì cuộc sống sinh tồn và phát triển tốt hơn của con người. Cùng với những chiến binh chính nghĩa khác, liên minh đối phó quái thú hung ác. Dưới tình cảnh tận thế, La Phong cùng với những chiến binh khác liệu có thể đẩy lùi quái thú, thành công bảo vệ thế giới loài người?',
			'Main: La Phong',
			'Vợ: Từ Hân',
			'Các cấp độ:',
			'– Trường phái: Vũ giả – Tinh Thần Niệm Sư (Bậc Thầy Tinh Thần) Khống Vật – Tinh Thần Niệm Sư (Bậc Thầy Tinh Thần) Huyễn thuật – Tề Dược Sư…',
			'– Trình độ địa cầu: Chiến sĩ – Chiến tướng – Chiến thần ( Trực thuộc cấp Học đồ )',
			'– Trình độ toàn vũ trụ:',
			'Học đồ – Hành tinh – Hằng tinh – Vũ trụ – Vực chủ – Giới chủ – Bất hủ – Bất hủ quân chủ – Bất hủ phong Hầu – Bất hủ phong Vương – Vũ trụ tôn giả – Vũ trụ bá chủ (Vũ trụ tôn giả vô địch) – Vũ trụ chi chủ (lực chiến 1-6) – Vũ trụ tối cường giả = Chân thần (lực chiến > 6) – Hư không chân thần (lực chiến > 10) – Vĩnh hằng chân thần – Hỗn Độn chúa tể – Thần vương – Hỗn nguyên – Lãnh chúa.',
		],
	},
	{
		releasedDate: new Date('2024-12-26'),
		name: 'Nghịch Thiên Chí Tôn',
		nameImg: require('../../assets/name-img/nghichthienchiton.png'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/09/nghich-thien-chi-ton-300x450.jpg',
		poster: 'https://audiotruyenfull.com/wp-content/uploads/2020/04/Ngh%E1%BB%8Bch-Thi%C3%AAn-Ch%C3%AD-T%C3%B4n.jpg',
		engName: 'Ni Tian Zhi Zun',
		types: ['Huyền huyễn', 'Trùng sinh', 'Cổ trang'],
		isRelease: true,
		description: [
			'Ngày xưa uy chấn chư thiên Thần Vực, vạn thế luân hồi sau thảm tao diệt môn! Tàn khốc nguyền rủa, vạn thế cừu hận, Đàm Vân lập chí, không còn trầm luân! Vì tình cảm chân thành, thân nhân, từ đây từng bước một giẫm lên cừu nhân thi thể siêu việt đỉnh phong! Nghịch thiên sát lục, tung hoành vạn giới, duy ta chí tôn! Gái gú thì khỏi nói…',
			'Main: Đàm Vân (kiếp trước là Hồng Mông Chí Tôn)',
			'Gái: Thẩm Tố Băng, Mục Mộng Nghệ ( Đường Mộng Nghệ), Chung Ngô Thi Dao (Tư Hồng Thi Dao), Nam Cung Ngọc Thấm, Đường Hinh Doanh, Hoàng Phủ Ngọc (Đàm Đài Tiên Nhi), Công Tôn Nhược Hi, Cơ Ngữ Yên, Hiên Viên Nhu, Âu Dương Thiên Thiên, Tiết Tử Yên, Đông Phương Ngọc Thấu, Phương Tử Hề, Ngu Vân Hề, Tân Băng Tuyền, Trưởng Tôn Hiên Thất (Hỗn Độn Chí Tôn), Phùng Khuynh Thành',
			'Cảnh giới tu luyện',
			'Phàm giới: Linh Thai Cảnh, Thai Hồn Cảnh, Luyện Hồn Cảnh, Thần Hồn Cảnh, Thánh Hồn Cảnh, Hồn Mạch Cảnh, Thần Mạch Cảnh, Thần Vực Cảnh, Vực Thai Cảnh, Vũ Hóa Cảnh ( mỗi cảnh giới chia làm 9 cấp và đại viên mãn)',
			'Tiên giới: Phạt Tiên Cảnh, Luyện Tiên Cảnh, Đế Nhân Cảnh, Đế Thánh Cảnh, Đế Vương Cảnh, Đế Hoàng Cảnh, Đại Đế Cảnh (mỗi cảnh giới chia từ cấp 1 đến 12)',
			'Thần giới: Nhân Thần Cảnh, Địa Thần Cảnh, Thiên Thần Cảnh, Bán Thánh Cảnh, Đại Thánh Cảnh, Thánh Vương Cảnh, Thánh Hoàng Cảnh, Thần Vương Cảnh, Vĩnh Hằng Cảnh ( mỗi cảnh giới chia từ cấp 1 đến 9)',
			'Vĩnh Hằng Hóa Vũ: Nhân Đạo Vạn Vật Cảnh – Thượng Thần Cảnh, Thiên Đạo Giới Phạt Cảnh – Thần Tôn Cảnh, Càn Khôn Hồng Mông Cảnh – Chí Tôn Cảnh, Thần Đạo Thủy Nguyên Cảnh – Tổ Thần Cảnh, Vạn Vật Hóa Hư Cảnh – Tổ Vương Cảnh',
			'Thế Giới Chí Cao: Tổ Hoàng Cảnh -Thương Thiên Chi Tôn , Tổ Đế Cảnh – Bá Vương Vũ Trụ, Tổ Thánh Cảnh, Đạo Nhân Cảnh, Đạo Thần Cảnh, Đạo Vương Cảnh, Đạo Hoàng Cảnh, Đạo Đế Cảnh, Đạo Thánh Cảnh, Đạo Tổ Cảnh, Chí Cao Đạo Tổ Cảnh',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/vo-than-chua-te-127-300x449.jpg',
		poster: 'https://vozradio.net/wp-content/uploads/2022/11/vo-than-chua-te-audio.jpg',
		nameImg: require('../../assets/name-img/vothanchuate.png'),
		name: 'Võ Thần Chúa Tể',
		engName: 'Wu Shen Zhu Zai',
		types: ['Cổ trang', 'huyền huyễn', 'trùng sinh'],
		isRelease: true,
		description: [
			'Thiên Vũ đại lục nhất đại truyền kỳ Tần Trần, bởi vì bạn tốt phản bội bất ngờ ngã xuống Võ vực. 300 năm sau, hắn chuyển sinh thành một con riêng ở một vương phủ phải chịu đủ mọi ức hiếp lên người, lợi dụng trình độ kiếp trước, ngưng thần công, luyện thần đan, đi ngược lên trời, quật khởi mạnh mẽ, từ đây bước lên một đoạn khiếp sợ đại lục kinh thế lữ trình.',
			'Đẳng cấp tu vi: Nhân cấp – Địa cấp – Thiên cấp – Huyền cấp – Võ Tông – Võ Tôn – Võ Vương – Võ Hoàng – Võ Đế – Phàm Thánh – Thánh – Thiên Thánh – Thánh Chủ – Tôn Giả – Chí Tôn (Mỗi cấp phân làm bán bộ – sơ kỳ – sơ kỳ đỉnh phong – trung kỳ – trung kỳ đỉnh phong – hậu kỳ – hậu kỳ đỉnh phong) Thánh cấp có thể phá nát hư không, phi thăng thiên giới.',
		],
	},
	{
		releasedDate: new Date('2024-12-26'),
		name: 'Đấu Phá Thương Khung Phần 5',
		nameImg: require('../../assets/name-img/dauphathuongkhung.png'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2022/06/dau-pha-thuong-khung-phan-5-gia-nam-hoc-vien-1-1-300x450.jpg',
		poster: 'https://thanhnien.mediacdn.vn/Uploaded/khuongduy/2018_05_21/dau-pha-thuong-khung-01_SSBV.jpg?width=600',
		engName: 'Fights Break Sphere 5',
		types: ['cổ trang', 'Huyền huyễn'],
		isRelease: true,
		description: [
			'Sau hẹn ước 3 năm, Tiêu Viêm cuối cùng cũng gặp được Huân Nhi ở học viện Già Nam, sau đó hắn kết giao nhiều bạn bè, thành lập Bàn Môn; vì tiếp tục nâng cao thực lực để lên Vân Lam Tông lần 3 báo thù cho cha, hắn mạo hiểm đi vào Thiên Phần luyện Khí Tháp thôn phệ Vẫn Lạc Tâm Viêm…',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2023/02/luyen-khi-10-van-nam-300x450.jpg',
		poster: 'https://lh4.googleusercontent.com/smEbpllB8sLuuG5TU-LAVCC8x1nk9-1INGtu8wK8HRjJifMM2mv6FhEVoMQYLfEoScOzoT44vKw4eXCHQPZxFDMEOuCi8MPQfMuzt1Cy0bhO_4v39eSx6AE2ELoFAB_deaI_BtXBAf1EXz1sDXV_CpA',
		nameImg: require('../../assets/name-img/luyenkhimuoivannam.png'),
		name: 'Luyện Khí Mười Vạn Năm',
		engName: 'KaTu',
		types: ['Cổ trang', 'tiên hiệp'],
		isRelease: true,
		description: [
			'Mười vạn năm trước Thiên Lam Tông vang dội giới tu chân, đệ tử trong tông đều là những đứa con của trời, đánh đâu thắng đó. Chỉ có khai sơn đệ tử Từ Dương vẫn luôn ở Luyện Khí kỳ, để đột phá tu vi sớm ngày phi thăng, Từ Dương bế quan vạn năm. Ai ngờ trong thời gian bế quan giới tu chân đã xuống dốc, Thiên Lam Tông cũng chỉ còn vài ba đệ tử, thấy sắp phải đối mặt với diệt tông, Từ Dương đánh bại cường địch, thề sẽ dẫn dắt Thiên Lam Tông quay về đỉnh cao!',
		],
	},
	{
		releasedDate: new Date('2024-12-26'),
		name: 'Phàm Nhân Tu Tiên Phần 3',
		nameImg: require('../../assets/name-img/phamnhantutien.png'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2022/11/pham-nhan-tu-tien-phan-3-1-300x450.png',
		poster: 'https://i.ytimg.com/vi/qjfcxPpUZ6c/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLC7flj-dGctr7wAnPF6tJ7PrUe5IQ',
		engName: 'Twin Martial Souls',
		types: ['Huyền huyễn', 'cổ trang', 'tiên hiệp'],
		isRelease: true,
		description: [
			'Khúc Hồn thành công kết đan! hai người ở Loạn Tinh hải còn gặp được cơ duyên gì gì? “Tinh Hải Phi Trì” , xin đợi trở về',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/04/the-gioi-hoan-my-tap-dac-biet-300x450.jpg',
		poster: 'https://hoathinh3d.pro/wp-content/uploads/2022/08/the-gioi-hoan-my.jpg',
		nameImg: require('../../assets/name-img/thegioihoanmy.png'),
		name: 'Thế Giới Hoàn Mỹ',
		engName: 'KaTu',
		types: ['Huyền huyễn', 'tiên hiệp'],
		isRelease: true,
		description: [
			'Thế Giới Hoàn Mỹ cải biên từ tiểu thuyết cùng tên. Hắn vì tu đạo mà sinh, vì ứng kiếp mà đến. Hắn hoá thân thành vô vàn mưa máu, vẩy rơi năm tháng vạn cổ, trải qua vô số tu luyện của thời không và thử thách của dòng chảy tháng năm. Hắn hoá thành vạn cổ, hoá thành tự tại. Xem nam chính Thạch Hạo làm thế nào đạt đến huy hoàng đỉnh cao một đời, tạo ra truyền thuyết vô tận.',
		],
	},
	{
		releasedDate: new Date('2024-12-26'),
		name: 'Sư Huynh A Sư Huynh',
		nameImg: require('../../assets/name-img/suhuynhasuhuynh.png'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2023/01/su-huynh-a-su-huynh-1-300x450.jpg',
		poster: 'https://i.ytimg.com/vi/VNja0QmfliI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAetH87ccVXJzKWUkGIOKDPG29qaw',
		engName: 'Twin Martial Souls',
		types: ['Huyền huyễn', 'cổ trang', 'hài hước'],
		isRelease: true,
		description: [
			'Nội dung kể về Lý Trường Thọ – một thanh niên mắc bệnh hiểm nghèo vô tình được tái sinh vào thời thượng cổ trước đại chiến phong thần, trở thành một Luyện khí sĩ. Vì để tu được trường sinh bất lão và sống yên thân nơi hồng hoang tàn khốc này mà hắn hành sự khiêm tốn, tính trước làm sau, trước giờ không bao giờ bước vào nơi nguy hiểm, giấu át chủ bài, tu độn thuật, luyện đan độc. Cho đến một hôm, sư phụ của hắn nhận một sư muội về cho hắn, Lý Trường Thọ vốn muốn khiêm tốn tu hành bị cuốn vào hiểm nguy.',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2022/04/than-an-vuong-toa-3-300x450.jpg',
		poster: 'https://image.tmdb.org/t/p/original/uLxe7AunjdkirdsdHjTQOUnhwG5.jpg',
		nameImg: require('../../assets/name-img/thananvuongtoa.png'),
		name: 'Thần Ấn Vương Tọa',
		engName: 'KaTu',
		types: ['Huyền huyễn', 'kiếm hiệp'],
		isRelease: true,
		description: [
			'Một thiếu niên vì cứu mẫu thân của mình mà gia nhập Kỵ Sĩ Thánh Điện, kỳ tích, quỷ kế không ngừng xoay quanh hắn. Trên con đường để giải cứu nhân loại và tìm đến đỉnh cao của tu luyện hắn đã đi tìm và giải đáp rất nhiều bí ẩn của đại lục.',
		],
	},
	{
		releasedDate: new Date('2024-12-26'),
		name: 'Già Thiên',
		nameImg: require('../../assets/name-img/giathien.png'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2022/10/gia-thien-5-300x450.jpg',
		poster: 'https://i.pinimg.com/originals/fe/ef/9a/feef9a672e98c0a2fb170cb59e81489b.jpg',
		engName: 'Twin Martial Souls',
		types: ['Huyền huyễn', 'tiên hiệp', 'xuyên không'],
		isRelease: true,
		description: [
			'Một chàng trai thành đạt được bạn bè yêu quý. Trong một lần họp mặt cùng nhóm bạn, một sự cố huyền ảo đã xảy ra và đưa cả nhóm bạn quay trở về thời cổ đại, thời kỳ tồn tại của những vị thần. Nơi đó, mọi mâu thuẫn chỉ có thể giải quyết bằng sức mạnh…Có tồn tại thế giới thần tiên này ư? Có phải đây chỉ là những truyền thuyết hay sự tích ? Những gì nhìn thấy là sự thật hay là ảo mộng.',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2022/07/tru-tien-phan-2-2024-300x450.jpg',
		poster: 'https://scontent.fhan15-1.fna.fbcdn.net/v/t39.30808-6/432778744_995629588825269_6081997374522451720_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=127cfc&_nc_ohc=QpIYhIkBitYQ7kNvgEzi8ki&_nc_ht=scontent.fhan15-1.fna&oh=00_AYCu4eIliCTZ4UG0q7-V-_IskoeCytcSQb-wMrN7vnauLw&oe=66DBF066',
		nameImg: require('../../assets/name-img/trutien.png'),
		name: 'Tru Tiên',
		engName: 'KaTu',
		types: ['Cổ trang', 'huyền huyễn', 'tiên hiệp'],
		isRelease: true,
		description: [
			'Chính ma đại chiến đã qua mười năm, Trương Tiểu Phàm hóa thân thành quỷ lệ, chinh phạt tứ phương trong nội đấu ma giáo. Lúc này dị bảo đầm lầy tử vong xuất thế, dẫn tới các thế lực tranh đoạt, Quỷ Lệ cùng Lục Tuyết Kỳ gặp lại, hai người lâm vào gút mắc yêu hận càng sâu.Sau đó Quỷ Lệ bởi vì chuyện cấp dưới mất tích mà điều tra tới Phần Hương cốc, ngoài ý muốn cứu ra Cửu Vĩ Thiên Hồ Tiểu Bạch, đạt được manh mối của Cổ Vu tộc,Quỷ Lệ trải qua cửu tử nhất sinh, cuối cùng cầu được đại vu sư nắm giữ chiêu hồn kỳ thuật đáp ứng đi tới cứu chữa Bích Dao, tâm nguyện mười năm, đến tột cùng kết quả như thế nào.',
		],
	},
	{
		releasedDate: new Date('2024-12-26'),
		name: 'Quyến Tư Lượng',
		nameImg: require('../../assets/name-img/quyentuluong.png'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/06/quyen-tu-luong-300x450.jpg',
		poster: 'https://i.ytimg.com/vi/pwW2QA0ali4/maxresdefault.jpg',
		engName: 'Twin Martial Souls',
		types: ['Huyền huyễn', 'tiên hiệp'],
		isRelease: true,
		description: [
			'Nội dung chính của Quyến Tư Lượng là hành trình nam chính Kính Huyền đi tìm sự thật về việc cha cậu năm xưa bày pháp trận phá kết giới của đảo Tư Lượng khiến rất nhiều người trên đảo bị hại chết. Kính Huyền luôn cho rằng có một kẻ bí ẩn phía sau đã hãm hại cha cậu. Nữ chính là phàm nhân tên Đồ Lệ, được cha Kính Huyền nhận nuôi từ nhỏ. Cô luôn phải đối mặt với chỉ trích của người trên đảo nên nhiều năm cố gắng tự đóng thuyền, mong vượt qua biển khơi tìm về một thế giới khác, thoát khỏi hòn đảo bi thương này.',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2023/06/thuong-nguyen-do-1-300x450.jpg',
		poster: 'https://thuvienanime.com/wp-content/uploads/2023/09/thuong-nguyen-do-thuvienanime-thumb.jpg',
		nameImg: require('../../assets/name-img/thuongnguyendo.png'),
		name: 'Thương Nguyên Đồ',
		engName: 'KaTu',
		types: ['Huyền huyễn', 'cổ trang'],
		isRelease: true,
		description: [
			'Nói về yêu tà hoành hành ở Thương Nguyên giới, loài người chịu đủ tàn phá, nam chính Mạnh Xuyên từ nhỏ đã lập lời thề phải báo thù cho mẫu thân. Lấy đạo viện Kính Hồ làm khởi điểm, dựa vào tâm chí kiên nghị không sợ hãi và thân thủ đao pháp nhanh nhạt, trừng phạt gian ác, tiêu diệt yêu tộc, đăng đỉnh tứ đại đạo viện, nổi danh Đông Minh phủ, bái Thượng Nguyên Sơ Sơn, trở thành một Thần Ma.',
		],
	},
	{
		releasedDate: new Date('2024-12-26'),
		name: 'Thần Lan Kỳ Vực Vô Song Châu',
		nameImg: require('../../assets/name-img/thanlankyvuc.png'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2022/07/than-lan-ky-vuc-vo-song-chau-ss3-300x450.jpg',
		poster: 'https://i.pinimg.com/736x/01/b4/34/01b4349ecda7b978a5e0fa9b4a163bbb.jpg',
		engName: 'Twin Martial Souls',
		types: ['Huyền huyễn'],
		isRelease: true,
		description: [
			'Năm 2501 Băng Hà, hành tinh sinh tồn của Ma tộc và Thú tộc va chạm đến đại lục Pháp Lam duy nhất-Yêu tinh đại lục. Tổ tiên con người sau khi tiên tri được thảm họa này. Hai tộc Yêu, Tinh liên hợp toàn bộ chủng tộc cùng nhau chế tạo ra thần khí Thất Thần Châu, đối kháng lại cú va chạm, tránh cho thế giới bị diệt vong. Yêu Tinh đại lục cùng với đó đã bị tan rã, trở thành thất hải lục vực. Hơn 300 năm sau kể từ trận thảm họa, Ma tộc dần dần thức tỉnh, bắt đầu thôn tính thất hải lục vực. Hai vị thiếu niên vô tình có được Vô Song Châu trong Thất Thần Châu, giúp bọn họ có năng lực triệu hồi lẫn nhau.',
		],
	},
];

export const top = [
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/thon-phe-tinh-khong-6-300x450.jpg',
		poster: 'https://image.tmdb.org/t/p/original/n40e0jtHdDCF2u8Kpps8K2Mx03B.jpg',
		nameImg: require('../../assets/name-img/thonphe.png'),
		name: 'Thôn Phệ Tinh Không',
		engName: 'Swallowed Star',
		types: ['Hiện Đại', 'Huyền huyễn'],
		isRelease: true,
		description: [
			'Một ngày nọ, thế giới xuất hiện loại virus RR không rõ lai lịch, cuốn thế giới vào thảm hoạ. Động vật bị truyền nhiễm đột biến thành quái thú đáng sợ, xâm lược với số lượng lớn. Trong lúc loài người đối mặt với diệt vong, họ đã xây lên bức tường bao vây, thành lập căn cứ làm pháo đài cuối cùng bảo vệ con người.',
			'Trong thời gian này, con người nếm trải đủ mọi khó khăn, được gọi là “thời kỳ Đại Niết Bàn”. Trong môi trường sinh tồn cực đoan, bản năng của con người cũng dần phát triển, ngọn gió thượng võ phất lên, tố chất cơ thể con người vượt trội hơn trước. Mà trong những người xuất sắc, được gọi là “chiến binh”. La Phong năm 18 tuổi cũng ước mơ trở thành một trong số họ. Cậu lúc này sắp phải thi đại học, đang đối diện với sự lựa chọn giữa ngã tư đời người. Nhưng lại bị quái thú tấn công ảnh hưởng quỹ đạo cuộc đời của cậu hết lần này đến lần khác.',
			'Dưới uy hiếp của quái thú, cư dân trong thành phố đối diện với nguy hiểm, quân sự lại bó tay. Duy chỉ có chiến binh xông pha, bảo vệ an toàn cho căn cứ. La Phong được những chiến binh truyền cảm hứng, âm thầm hạ quyết tâm trở thành chiến binh bảo vệ người mình yêu thương. Đây chính là khởi đầu của mọi thứ, khởi điểm của  con đường chiến binh La Phong, cũng vén bức màn cuộc đời truyền kì của cậu. La Phong lập chí trở thành chiến binh. Con đường phía không dễ dàng, đầu tiên cậu phải đối diện với môi trường ngoại bộ, vô hình chung càng thêm ảnh hưởng tới cậu. Gia đình La Phong có điều kiện không tốt, cuộc sống túng thiếu, bố mẹ không thể giúp đỡ cậu được nhiều, cậu đành dựa vào nỗ lực của bản thân.',
			'Cuối cùng, dưới sự khổ luyện, La Phong không ngừng khai quật ra tiềm năng của mình, nhận được sự nâng cấp năng lực với sự công nhận giá trị bản thân. Không những vậy, La Phong còn gánh vác gánh nặng nuôi dưỡng  gia đình, cũng vì bảo vệ tổ quốc loài người, vì cuộc sống sinh tồn và phát triển tốt hơn của con người. Cùng với những chiến binh chính nghĩa khác, liên minh đối phó quái thú hung ác. Dưới tình cảnh tận thế, La Phong cùng với những chiến binh khác liệu có thể đẩy lùi quái thú, thành công bảo vệ thế giới loài người?',
			'Main: La Phong',
			'Vợ: Từ Hân',
			'Các cấp độ:',
			'– Trường phái: Vũ giả – Tinh Thần Niệm Sư (Bậc Thầy Tinh Thần) Khống Vật – Tinh Thần Niệm Sư (Bậc Thầy Tinh Thần) Huyễn thuật – Tề Dược Sư…',
			'– Trình độ địa cầu: Chiến sĩ – Chiến tướng – Chiến thần ( Trực thuộc cấp Học đồ )',
			'– Trình độ toàn vũ trụ:',
			'Học đồ – Hành tinh – Hằng tinh – Vũ trụ – Vực chủ – Giới chủ – Bất hủ – Bất hủ quân chủ – Bất hủ phong Hầu – Bất hủ phong Vương – Vũ trụ tôn giả – Vũ trụ bá chủ (Vũ trụ tôn giả vô địch) – Vũ trụ chi chủ (lực chiến 1-6) – Vũ trụ tối cường giả = Chân thần (lực chiến > 6) – Hư không chân thần (lực chiến > 10) – Vĩnh hằng chân thần – Hỗn Độn chúa tể – Thần vương – Hỗn nguyên – Lãnh chúa.',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2023/09/tien-nghich-2-300x450.jpg',
		poster: 'https://homepage.momocdn.net/blogscontents/momo-amazone-s3-api-240819164320-638596826005331876.jpeg',
		nameImg: require('../../assets/name-img/tiennghich.png'),
		name: 'Tiên Nghịch',
		engName: 'Swallowed Star',
		types: ['Cổ trang', 'Huyền huyễn', 'tiên hiệp'],
		isRelease: true,
		description: [
			'Cải biên từ tiểu thuyết “Tiên Nghịch” của tác giả Nhĩ Căn, kể về thiếu niên bình phàm Vương Lâm xuất thân nông thôn, mang theo nhiệt huyết, tu luyện nghịch tiên, không chỉ cầu trường sinh, mà còn muốn thoát khỏi thân phận giun dế. Hắn tin rằng đạo do người quyết định, dùng tư chất bình phàm bước vào con đường tu chân, trải qua bao phong ba bão táp, dựa vào trí tuệ sáng suốt, từng bước một bước lên đỉnh cao, dựa vào sức một người, danh chấn Tu chân giới.',
		],
	},
	{
		releasedDate: new Date('2024-12-26'),
		name: 'Đấu Phá Thương Khung Phần 5',
		nameImg: require('../../assets/name-img/dauphathuongkhung.png'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2022/06/dau-pha-thuong-khung-phan-5-gia-nam-hoc-vien-1-1-300x450.jpg',
		poster: 'https://thanhnien.mediacdn.vn/Uploaded/khuongduy/2018_05_21/dau-pha-thuong-khung-01_SSBV.jpg?width=600',
		engName: 'Fights Break Sphere 5',
		types: ['cổ trang', 'Huyền huyễn'],
		isRelease: true,
		description: [
			'Sau hẹn ước 3 năm, Tiêu Viêm cuối cùng cũng gặp được Huân Nhi ở học viện Già Nam, sau đó hắn kết giao nhiều bạn bè, thành lập Bàn Môn; vì tiếp tục nâng cao thực lực để lên Vân Lam Tông lần 3 báo thù cho cha, hắn mạo hiểm đi vào Thiên Phần luyện Khí Tháp thôn phệ Vẫn Lạc Tâm Viêm…',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/04/the-gioi-hoan-my-tap-dac-biet-300x450.jpg',
		poster: 'https://hoathinh3d.pro/wp-content/uploads/2022/08/the-gioi-hoan-my.jpg',
		nameImg: require('../../assets/name-img/thegioihoanmy.png'),
		name: 'Thế Giới Hoàn Mỹ',
		engName: 'KaTu',
		types: ['Huyền huyễn', 'tiên hiệp'],
		isRelease: true,
		description: [
			'Thế Giới Hoàn Mỹ cải biên từ tiểu thuyết cùng tên. Hắn vì tu đạo mà sinh, vì ứng kiếp mà đến. Hắn hoá thân thành vô vàn mưa máu, vẩy rơi năm tháng vạn cổ, trải qua vô số tu luyện của thời không và thử thách của dòng chảy tháng năm. Hắn hoá thành vạn cổ, hoá thành tự tại. Xem nam chính Thạch Hạo làm thế nào đạt đến huy hoàng đỉnh cao một đời, tạo ra truyền thuyết vô tận.',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2023/06/dau-la-dai-luc-phan-2-1-300x450.jpg',
		poster: 'https://i.ytimg.com/vi/1OGRZcM0Nfk/maxresdefault.jpg',
		nameImg: require('../../assets/name-img/dauladailuc.png'),
		name: 'Đấu La Đại Lục 2: Tuyệt Thế Đường Môn',
		engName: 'KaTu',
		types: ['Huyền huyễn'],
		isRelease: true,
		description: [
			'Nơi này không có ma pháp, không có đấu khí, không có võ thuật, lại có võ hồn. Đường Môn sáng lập vạn năm trên Đấu La đại lục, Đường Môn suy thoái. Một đời Thiên Kiêu hoành không xuất thế, Sử Lai Khắc thất quái đời mới có thể hồi sinh được Đường Môn, viết một khúc nhạc về Tuyệt Thế Đường Môn..',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2023/03/tien-vo-de-ton-p2-300x450.jpg',
		poster: 'https://thuvienanime.com/wp-content/uploads/2024/05/tien-vo-de-ton-truyen-thuvienanime-thumb.jpg',
		nameImg: require('../../assets/name-img/tienvodeton.png'),
		name: 'Tiên Võ Đế Tôn',
		engName: 'KaTu',
		types: ['Huyền huyễn', 'tiên hiệp'],
		isRelease: true,
		description: [
			'Chín ngàn năm trước, Tiên Võ Đế Tôn suất lĩnh trăm vạn Thần Tướng đánh vào Thái Cổ Hồng Hoang, lại không một người trở về, chỉ có một sợi chân hỏa còn sót lại thế gian.',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2022/04/than-an-vuong-toa-3-300x450.jpg',
		poster: 'https://image.tmdb.org/t/p/original/uLxe7AunjdkirdsdHjTQOUnhwG5.jpg',
		nameImg: require('../../assets/name-img/thananvuongtoa.png'),
		name: 'Thần Ấn Vương Tọa',
		engName: 'KaTu',
		types: ['Huyền huyễn', 'kiếm hiệp'],
		isRelease: true,
		description: [
			'Một thiếu niên vì cứu mẫu thân của mình mà gia nhập Kỵ Sĩ Thánh Điện, kỳ tích, quỷ kế không ngừng xoay quanh hắn. Trên con đường để giải cứu nhân loại và tìm đến đỉnh cao của tu luyện hắn đã đi tìm và giải đáp rất nhiều bí ẩn của đại lục.',
		],
	},
	{
		releasedDate: new Date('2024-12-26'),
		name: 'Phàm Nhân Tu Tiên Phần 3',
		nameImg: require('../../assets/name-img/phamnhantutien.png'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2022/11/pham-nhan-tu-tien-phan-3-1-300x450.png',
		poster: 'https://i.ytimg.com/vi/qjfcxPpUZ6c/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLC7flj-dGctr7wAnPF6tJ7PrUe5IQ',
		engName: 'Twin Martial Souls',
		types: ['Huyền huyễn', 'cổ trang', 'tiên hiệp'],
		isRelease: true,
		description: [
			'Khúc Hồn thành công kết đan! hai người ở Loạn Tinh hải còn gặp được cơ duyên gì gì? “Tinh Hải Phi Trì” , xin đợi trở về',
		],
	},
	{
		releasedDate: new Date('2024-12-26'),
		name: 'Nghịch Thiên Chí Tôn',
		nameImg: require('../../assets/name-img/nghichthienchiton.png'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/09/nghich-thien-chi-ton-300x450.jpg',
		poster: 'https://audiotruyenfull.com/wp-content/uploads/2020/04/Ngh%E1%BB%8Bch-Thi%C3%AAn-Ch%C3%AD-T%C3%B4n.jpg',
		engName: 'Ni Tian Zhi Zun',
		types: ['Huyền huyễn', 'Trùng sinh', 'Cổ trang'],
		isRelease: true,
		description: [
			'Ngày xưa uy chấn chư thiên Thần Vực, vạn thế luân hồi sau thảm tao diệt môn! Tàn khốc nguyền rủa, vạn thế cừu hận, Đàm Vân lập chí, không còn trầm luân! Vì tình cảm chân thành, thân nhân, từ đây từng bước một giẫm lên cừu nhân thi thể siêu việt đỉnh phong! Nghịch thiên sát lục, tung hoành vạn giới, duy ta chí tôn! Gái gú thì khỏi nói…',
			'Main: Đàm Vân (kiếp trước là Hồng Mông Chí Tôn)',
			'Gái: Thẩm Tố Băng, Mục Mộng Nghệ ( Đường Mộng Nghệ), Chung Ngô Thi Dao (Tư Hồng Thi Dao), Nam Cung Ngọc Thấm, Đường Hinh Doanh, Hoàng Phủ Ngọc (Đàm Đài Tiên Nhi), Công Tôn Nhược Hi, Cơ Ngữ Yên, Hiên Viên Nhu, Âu Dương Thiên Thiên, Tiết Tử Yên, Đông Phương Ngọc Thấu, Phương Tử Hề, Ngu Vân Hề, Tân Băng Tuyền, Trưởng Tôn Hiên Thất (Hỗn Độn Chí Tôn), Phùng Khuynh Thành',
			'Cảnh giới tu luyện',
			'Phàm giới: Linh Thai Cảnh, Thai Hồn Cảnh, Luyện Hồn Cảnh, Thần Hồn Cảnh, Thánh Hồn Cảnh, Hồn Mạch Cảnh, Thần Mạch Cảnh, Thần Vực Cảnh, Vực Thai Cảnh, Vũ Hóa Cảnh ( mỗi cảnh giới chia làm 9 cấp và đại viên mãn)',
			'Tiên giới: Phạt Tiên Cảnh, Luyện Tiên Cảnh, Đế Nhân Cảnh, Đế Thánh Cảnh, Đế Vương Cảnh, Đế Hoàng Cảnh, Đại Đế Cảnh (mỗi cảnh giới chia từ cấp 1 đến 12)',
			'Thần giới: Nhân Thần Cảnh, Địa Thần Cảnh, Thiên Thần Cảnh, Bán Thánh Cảnh, Đại Thánh Cảnh, Thánh Vương Cảnh, Thánh Hoàng Cảnh, Thần Vương Cảnh, Vĩnh Hằng Cảnh ( mỗi cảnh giới chia từ cấp 1 đến 9)',
			'Vĩnh Hằng Hóa Vũ: Nhân Đạo Vạn Vật Cảnh – Thượng Thần Cảnh, Thiên Đạo Giới Phạt Cảnh – Thần Tôn Cảnh, Càn Khôn Hồng Mông Cảnh – Chí Tôn Cảnh, Thần Đạo Thủy Nguyên Cảnh – Tổ Thần Cảnh, Vạn Vật Hóa Hư Cảnh – Tổ Vương Cảnh',
			'Thế Giới Chí Cao: Tổ Hoàng Cảnh -Thương Thiên Chi Tôn , Tổ Đế Cảnh – Bá Vương Vũ Trụ, Tổ Thánh Cảnh, Đạo Nhân Cảnh, Đạo Thần Cảnh, Đạo Vương Cảnh, Đạo Hoàng Cảnh, Đạo Đế Cảnh, Đạo Thánh Cảnh, Đạo Tổ Cảnh, Chí Cao Đạo Tổ Cảnh',
		],
	},
	{
		releasedDate: new Date('2024-9-20'),
		src: 'https://hoathinh3d.run/wp-content/uploads/2022/07/tru-tien-phan-2-2024-300x450.jpg',
		poster: 'https://scontent.fhan15-1.fna.fbcdn.net/v/t39.30808-6/432778744_995629588825269_6081997374522451720_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=127cfc&_nc_ohc=QpIYhIkBitYQ7kNvgEzi8ki&_nc_ht=scontent.fhan15-1.fna&oh=00_AYCu4eIliCTZ4UG0q7-V-_IskoeCytcSQb-wMrN7vnauLw&oe=66DBF066',
		nameImg: require('../../assets/name-img/trutien.png'),
		name: 'Tru Tiên',
		engName: 'KaTu',
		types: ['Cổ trang', 'huyền huyễn', 'tiên hiệp'],
		isRelease: true,
		description: [
			'Chính ma đại chiến đã qua mười năm, Trương Tiểu Phàm hóa thân thành quỷ lệ, chinh phạt tứ phương trong nội đấu ma giáo. Lúc này dị bảo đầm lầy tử vong xuất thế, dẫn tới các thế lực tranh đoạt, Quỷ Lệ cùng Lục Tuyết Kỳ gặp lại, hai người lâm vào gút mắc yêu hận càng sâu.Sau đó Quỷ Lệ bởi vì chuyện cấp dưới mất tích mà điều tra tới Phần Hương cốc, ngoài ý muốn cứu ra Cửu Vĩ Thiên Hồ Tiểu Bạch, đạt được manh mối của Cổ Vu tộc,Quỷ Lệ trải qua cửu tử nhất sinh, cuối cùng cầu được đại vu sư nắm giữ chiêu hồn kỳ thuật đáp ứng đi tới cứu chữa Bích Dao, tâm nguyện mười năm, đến tột cùng kết quả như thế nào.',
		],
	},
];
