export const data = [
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2024/08/IMG_0534-300x449.png',
		name: 'Niệm vô song',
		engName: 'A moment But Forever',
		episode: '4',
		update: [2],
	},
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/09/nghich-thien-chi-ton-300x450.jpg',
		name: 'Nghịch thiên chí tôn',
		engName: 'Ni Tian Zhi Zun',
		episode: '4',
		update: [2],
	},
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/doc-bo-tieu-dao-300x450.jpg',
		name: 'Độc bộ tiêu dao',
		engName: 'Du Bu Xiao Yao',
		episode: '4',
		update: [3],
	},
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/12/kiem-vuc-phong-van-ss-2-300x450.jpg',
		name: 'Kiếm vực phong vân',
		engName: 'The Legend of Sword Domain',
		episode: '4',
		update: [3],
	},
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2024/07/dai-luc-linh-vo1-300x449.jpg',
		name: 'Đại lục linh võ',
		engName: 'Lingwu Continent',
		episode: '4',
		update: [2],
	},
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2024/04/tan-tu-chi-vuong-300x450.jpg',
		name: 'Tán tu chi vương',
		engName: 'San Xiu Zhi Wang',
		episode: '4',
		update: [2],
	},
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2022/08/van-co-than-thoai-1-300x450.jpg',
		name: 'Vạn cổ thần thoại',
		engName: 'Wangu Shenhua',
		episode: '4',
		update: [4],
	},
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2024/06/kim-tam-vang-su-300x450.jpg',
		name: 'Kim tàm vãng sự',
		engName: 'Jin Can Wangshi',
		episode: '4',
		update: [2],
	},
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/vo-thuong-than-de-1-300x450.jpg',
		name: 'Vô thượng thần đế',
		engName: 'Wu Shang Shen Di',
		episode: '4',
		update: [5],
	},
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2024/06/IMG_0531.png',
		name: 'Lục địa kiện tiên',
		engName: 'Keyboard Immortal',
		episode: '4',
		update: [2],
	},
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/02/van-gioi-tien-tung-300x450.webp',
		name: 'Vạn giới tiên tung',
		engName: 'Wan Jie Xian Zong',
		episode: '4',
		update: [2],
	},
	{
		src: 'https://hoathinh3d.run/wp-content/uploads/2021/09/cuu-thien-huyen-de-quyet-3-300x450.jpg',
		name: 'Cửu thiên huyền đế hoàng',
		engName: 'The Success Of Empyrean Xuan Emperor',
		episode: '4',
		update: [2],
	},
];
